title: jekyll-rtd-theme
lang: en
description: GitHub-flavored docs theme for Jekyll

theme: null

nav_version: true
edit: true
addons_branch: true

addons:
  - github
  - i18n
  - plugins
  - analytics

copyright:
  revision: true

debug: true

readme_index:
  with_frontmatter: true

sass:
  style: compressed

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
