title: jekyll-rtd-theme
lang: en
description: Opinionated github flavored documentation theme for open source projects

theme: null

# debug:
#   compress: true
#   dist: false
#   extension: true

readme_index:
  with_frontmatter: true

sass:
  style: compress

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
